name: Context

permissions: 
    repository-projects: read

on:
  workflow_dispatch:


   
jobs:
  info:
    runs-on: ubuntu-latest
    name: Context Pipe
    steps:
      - name: get context
        run: echo "${{ toJSON(github) }}"
        