
name: Test custom action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Check code action
          uses: ./.github/actions/check-code-docker
        # - name: Check code action
        #   uses: ./.github/actions/check-code-composite